### ISSUE TITLE
Error when build proyect

### ISSUE THREAD

**Issue by jgcorrales** [MOLO17/CustomizableCalendar#10]
I have cloned your github project and updated the dependencies to the latest versions, but when I run the sample I skip this error:

Error:Execution failed for task ':library:transformClassesWithRetrolambdaForDebug'.
> Missing javaCompileTask for variant: debug/0 from output dir: /Users/juangra/Proyectos/Proyectos_pruebas/CustomizableCalendar-master/library/build/intermediates/transforms/retrolambda/debug/0

My pc is mac and Android studio is 3.0.
Help me please.

**Comment by francesco-furlan** [comment]
Hi @jgcorrales can you try the last release v0.1.4?
