### ISSUE TITLE
Reset Calendar

### ISSUE THREAD

**Issue by smaske1992** [MOLO17/CustomizableCalendar#12]
How do we clear the selection ?

**Comment by francesco-furlan** [comment]
Hi @smaske1992 and sorry for the delay, to clear the selection you can use `setFirstSelectedDay` and `setLastSelectedDay` methods of `AUCalendar` and pass them `null` as parameter

**Comment by kaustubhkadam** [comment]
and how do we disable dates ?

**Comment by francesco-furlan** [comment]
@kaustubhkadam you can use this methods of `ViewInteractor` interface that you've implemented:
- `boolean hasImplementedSelection();` -> should return `true`
- `int setSelected(boolean multipleSelection, DateTime dateSelected);`
    -> return `0` if the date passed as param should be the first date selected;
    -> return `1` if the date passed as param should be the last date selected;
    -> return any other number if the date passed as param shouldn't be selected;
