### ISSUE TITLE
Unable to sync the gradle

### ISSUE THREAD

**Issue by rajasekaranm** [MOLO17/CustomizableCalendar#21]
Hi ,

I'm unable to sync the project because I'm getting **`Manifest merge`** error

Kindly check the error log

`Manifest merger failed : Attribute application@allowBackup value=(false) from AndroidManifest.xml:15:9-36
	is also present at [com.github.MOLO17:CustomizableCalendar:v0.1.4] AndroidManifest.xml:12:9-35 value=(true).
	Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at AndroidManifest.xml:13:5-160:19 to override.`

**Additional Info :**  I can able to sync the gradle if I used `android:allowBackup="true"` in my app manifest. but I need to set `allowBackup` as `false`

Thanks in advance

**Comment by francesco-furlan** [comment]
Hi @rajasekaranm,
I've removed the `allowBackup` attribute on the manifest, you can test the `v0.1.5` version.

**Comment by rajasekaranm** [comment]
yes @furlan97 , now working fine :-) thanks
