### ISSUE TITLE
Unable to unselect the date 

### ISSUE THREAD

**Issue by rajasekaranm** [MOLO17/CustomizableCalendar#22]
Hi,

I unable to choose the new date as start date if it's greater than previous one.

[device-2018-05-14-152347.zip](https://github.com/MOLO17/CustomizableCalendar/files/2000186/device-2018-05-14-152347.zip)

**Comment by francesco-furlan** [comment]
Hi,
if you want to customize the selection, you need to return `true` on the `hasImplementedSelection` method and implement the `setSelected` method based on your needs, these methods could be found in your "CalendarViewInteractor" which implements `ViewInteractor`.

**Comment by rajasekaranm** [comment]
okay thanks @furlan97 .
