### ISSUE TITLE
How to change the selection color from default blue 

### ISSUE THREAD

**Issue by sharathyadhav1** [MOLO17/CustomizableCalendar#24]
How to change the selection color from default blue  and also the  selection text color in the recycle view of CalendarRecyclerView

**Comment by francesco-furlan** [comment]
Hi @sharathyadhav1, you can find the default implementation in the `MonthAdapter` class of the library starting on line `93`, to customize the background and the text color you should return `true` on the `hasImplementedMonthCellBinding` method and implement the `onMonthCellBindView` method of your `ViewInteractor`.

**Comment by sharathyadhav1** [comment]
thanks  it worked
