### ISSUE TITLE
Invoke-customs are only supported starting with Android O 

### ISSUE THREAD

**Issue by vivekpchrome** [MOLO17/CustomizableCalendar#25]
Getting this error , Invoke-customs are only supported starting with Android O (--min-api 26)
Message{kind=ERROR, text=Invoke-customs are only supported starting with Android O (--min-api 26), sources=[Unknown source file], tool name=Optional.of(D8)}

**Comment by francesco-furlan** [comment]
Hi @vivekpchrome have you tried this https://stackoverflow.com/questions/49891730/invoke-customs-are-only-supported-starting-with-android-0-min-api-26/50198499 ?

**Comment by vivekpchrome** [comment]
Yes I have tried but after applying that I am getting new errors , I have resolved this issue by adding "compile "io.reactivex.rxjava2:rxjava:+"  to build.gradle

**Comment by vivekpchrome** [comment]
Now I am facing a new issue . the calender  is showing wrong colors I have changed from xml but not 
![screenshot_1534396146](https://user-images.githubusercontent.com/40761294/44189558-36415e80-a141-11e8-97cf-531864f23a1e.png)

**Comment by francesco-furlan** [comment]
Hi @vivekpchrome, can you close this issue and open another for that?
I need some more infos to answer you:
- how/where did you change the color?
- did you implemented the `onMonthCellBindView` of your `ViewInteractor` and did you `return true` on the `hasImplementedMonthCellBinding`?

Thanks in advance
