### ISSUE TITLE
To choose a one day

### ISSUE THREAD

**Issue by Khodanovich** [MOLO17/CustomizableCalendar#31]
Hello. How can I choose a one day? I do not use a range days. Thanks)

**Comment by Khodanovich** [comment]
calendar.setMultipleSelection(false)

**Comment by francesco-furlan** [comment]
Hi,
Yep you can use `calendar.setMultipleSelection(false)` combined with `calendar.setFirstSelectedDay(...)`

**Comment by Khodanovich** [comment]
Thanks you very mach)))

**Comment by Khodanovich** [comment]
Hello. I did calendar.setMultipleSelection(false) but it don not working for me. Where can i be wrong?
