### ISSUE TITLE
inflating class

### ISSUE THREAD

**Issue by eslamwael74** [MOLO17/CustomizableCalendar#5]
whenrun app please help
Error inflating class com.molo17.customizablecalendar.library.components.CustomizableCalendar

**Comment by francesco-furlan** [comment]
Hi @eslamwael74,
did you use only the `CustomizableCalendar` layout without adding `app:layout="@layout/your_layout"` ?
If yes please check if your dependencies are at the latest version, in particular `Butterknife`.
If no please check if all the ids are there as specified in the README.md (note that all ids are required).
Let me know if this solves your problem.

**Comment by eslamwael74** [comment]
done but solved it when adding in my dependencies for RXJava.
new issue in my locale days didn't showing i am from Egypt

**Comment by francesco-furlan** [comment]
Oh I see, let's open another issue for that.
