### ISSUE TITLE
Need help implementing a vertical calendar view

### ISSUE THREAD

**Issue by akul1994** [MOLO17/CustomizableCalendar#7]
Hey, I need help implementing a vertically scrollable version of the calendar view. I've set the layout manager of the recycler view as vertical. this got me a vertically scrollable implementation, however on scrolling up and down the view is breaking and not rendering as required. can you help me with this? attached screenshots, ignore other customisations i've added. irrelevant here.

![screenshot_1505905215](https://user-images.githubusercontent.com/9698473/30640565-08806f82-9e21-11e7-83a2-c9a66adec948.png)

after scolling

![screenshot_1505905219](https://user-images.githubusercontent.com/9698473/30640570-0e7e674a-9e21-11e7-867d-8db16635e0fb.png)

**Comment by francesco-furlan** [comment]
Hi @akul1994,
I noticed that there's a bug in the library.
In the meantime you can use `getLayoutManager` method and then set to it the vertical orientation.
