### ISSUE TITLE
can't import 

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [MOLO17/CustomizableCalendar#8]
![image](https://user-images.githubusercontent.com/5357526/31931473-00ded4b2-b8ac-11e7-99ed-ab113424f57a.png)

**Comment by francesco-furlan** [comment]
I cannot reproduce this error, using Android Studio 3 RC2 and updating all dependencies it's working fine... have you tried to clean the project and/or "Invalidate Caches/Restart..."  Android Studio?

**Comment by AndroidDeveloperLB** [comment]
I've now installed Android Studio 3.0 final version:
Android Studio 3.0
Build #AI-171.4408382, built on October 20, 2017
JRE: 1.8.0_152-release-915-b01 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

Tried to clone the repo again, opened it, and got the same error.
I've updated all of the things I could on the library and the sample modules.
And... I still got this issue:

![image](https://user-images.githubusercontent.com/5357526/32044215-9b751fd2-ba45-11e7-9b3c-fdaa4e154792.png)

**Comment by francesco-furlan** [comment]
Hi @AndroidDeveloperLB can you try the last release v0.1.4?

**Comment by AndroidDeveloperLB** [comment]
@furlan97 I've cloned it again, now. Seems to work fine.
But please don't close issue without letting to reply.

**Comment by AndroidDeveloperLB** [comment]
btw, I think the sample has an issue:
I can't set a different from-start date, that's not earlier than the current one.
